-- Created on 2/25/2020 by DIEGO 


-- ESPECIFICAÇÃO DA PACKAGE --

CREATE OR REPLACE PACKAGE PKG_ALUNO
 IS
  vCidade VARCHAR2(30);
  vMedia NUMBER(8,2);
  vNome VARCHAR2(30);
PROCEDURE DELETA_ALUNO(pCOD_ALUNO NUMBER);
PROCEDURE MEDIA_CONTRATOS;
PROCEDURE CON_ALUNO(pCOD_ALUNO NUMBER);
END;

-- CORPO DA PACKAGE --

CREATE OR REPLACE PACKAGE BODY PKG_ALUNO
 IS

vTeste VARCHAR2(20);

PROCEDURE MEDIA_CONTRATOS
 IS
BEGIN
	vTeste := 'teste';
  SELECT AVG(TOTAL) INTO vMedia FROM TCONTRATO;	
END; 


PROCEDURE CON_ALUNO(pCOD_ALUNO NUMBER)
 IS
BEGIN
	vNome := '';
  SELECT NOME INTO vNome FROM TALUNO WHERE COD_ALUNO = pCOD_ALUNO;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    dbms_output.put_line('Aluno não existe!');
END;


PROCEDURE DELETA_ALUNO(pCOD_ALUNO NUMBER)
  IS
BEGIN
  CON_ALUNO(pCOD_ALUNO);
  IF LENGTH (vNome) > 0 THEN
    DELETE FROM TALUNO WHERE COD_ALUNO = pCOD_ALUNO;
    dbms_output.put_line(vNome || ' -> Excluido');
  END IF;
 END;
 
END;

EXECUTE PKG_ALUNO.DELETA_ALUNO(99);


SELECT * FROM TALUNO;


DECLARE
  m NUMBER;
BEGIN
  PKG_ALUNO.MEDIA_CONTRATOS;
  m := PKG_ALUNO.vMedia;
  dbms_output.put_line('Média: ' || m);
END;  
  
  
DECLARE
  nome VARCHAR2(30);
BEGIN
  PKG_ALUNO.CON_ALUNO(89);
  nome := PKG_ALUNO.vNome;
  dbms_output.put_line('Nome ' || nome);
END; 

BEGIN
  PKG_ALUNO.CON_ALUNO(1);
  dbms_output.put_line('Nome ' || PKG_ALUNO.vNome);   
END;  



