CREATE TABLE TALUNO(

    COD_ALUNO INTEGER NOT NULL,
    NOME VARCHAR(30),
    CIDADE VARCHAR(30),
    CEP VARCHAR(10),
    PRIMARY KEY(COD_ALUNO)
);

 SELECT * FROM TALUNO;

/*
INSERT INTO TALUNO VALUES (1, 'Emília','Recife', '55.147-33');
INSERT INTO TALUNO VALUES (2, 'Patrícia','Recife', '55.326-33');
INSERT INTO TALUNO VALUES (3, 'Ellen', 'São Paulo' ,'55.266-33');
INSERT INTO TALUNO VALUES (4, 'João','São Paulo', '55.777-33');
*/


CREATE TABLE TCURSO(

    COD_CURSO INTEGER NOT NULL PRIMARY KEY,
    NOME VARCHAR(30),
    VALOR NUMBER(8,2),
    CARGA_HORARIA INTEGER
);

SELECT * FROM TCURSO;

-- UPDATE TALUNO SET nome = 'Emília' WHERE cod_aluno = 9658;

/*
INSERT INTO TCURSO VALUES(2, 'Java', 500.00, 36);
INSERT INTO TCURSO VALUES(3, 'Python', 500.00, 36);
INSERT INTO TCURSO VALUES(4, 'JavaScript', 500.00, 36);
INSERT INTO TCURSO VALUES(5, 'PHP', 500.00, 36);
INSERT INTO TCURSO VALUES(6, 'Angular', 500.00, 36);
INSERT INTO TCURSO VALUES(7, 'SQL', 500.00, 36);

*/

/*
UPDATE TCURSO SET carga_horaria = 28 WHERE cod_curso IN(3, 5);

UPDATE TCURSO SET valor = 800.00 ,carga_horaria = 45 WHERE cod_curso > 6;

UPDATE TCURSO SET valor = 1050.00 ,carga_horaria = 48 WHERE cod_curso > 5 AND cod_curso < 7

*/

SELECT SYSDATE FROM DUAL;

CREATE TABLE TCONTRATO(
    
    COD_CONTRATO INTEGER NOT NULL PRIMARY KEY,
    DATA DATE,
    COD_ALUNO INTEGER,
    TOTAL NUMBER(8,2),
    DESCONTO NUMBER(5,2)

);

SELECT * FROM tcontrato;

INSERT INTO tcontrato VALUES (2, SYSDATE, 1,800,16);
INSERT INTO tcontrato VALUES (3, SYSDATE, 1,1000,24);
INSERT INTO tcontrato VALUES (4, SYSDATE, 1,775,48);
INSERT INTO tcontrato VALUES (5, SYSDATE, 1,663,30);
INSERT INTO tcontrato VALUES (6, SYSDATE, 1,857,32);
INSERT INTO tcontrato VALUES (7, SYSDATE, 1,900,42);
INSERT INTO tcontrato VALUES (8, SYSDATE, 1,700,23);


------------------------------------------------------------

SELECT * FROM tcontrato;

SELECT * FROM TALUNO;

ALTER TABLE TCONTRATO ADD COL_TESTE VARCHAR(50);

ALTER TABLE TALUNO DROP COLUMN COL_TESTE;

ALTER TABLE TALUNO RENAME COLUMN NOME TO NOME2;

ALTER TABLE TALUNO RENAME COLUMN NOME2 TO NOME;


-- DROP TABLE ALUNO;

------------------------------------

-- SEQUENCE 

CREATE SEQUENCE SEQ_ALUNO START WITH 4;


INSERT INTO TALUNO(COD_ALUNO, NOME, CIDADE, CEP) 
VALUES (SEQ_ALUNO.nextval, 'Fernanda', 'Ibura', '5523133');


SELECT SEQ_ALUNO.CURRVAL FROM DUAL;

SELECT SYSDATE FROM DUAL;


-----------------------------

COMMIT;

SELECT * FROM TALUNO;

DELETE FROM TALUNO;

ROLLBACK;


SELECT * FROM TALUNO;

DELETE FROM taluno WHERE cod_aluno = 4;

ROLLBACK;


SELECT * FROM TALUNO WHERE NOME = 'João';

DELETE FROM TALUNO WHERE NOME = 'João';

COMMIT;

ROLLBACK;


--------------------------------------

CREATE TABLE TITEM
(
    COD_ITEM INTEGER NOT NULL PRIMARY KEY,
    COD_CURSO INTEGER,
    COD_CONTRATO INTEGER,
    VALOR NUMBER(8,2)
);


SELECT * FROM TITEM; 

INSERT INTO titem VALUES (1,1,1,500);
INSERT INTO titem VALUES (2,2,2,500);
INSERT INTO titem VALUES (3,3,3,1500);
INSERT INTO titem VALUES (4,4,4,1600);
INSERT INTO titem VALUES (5,1,5,500);
INSERT INTO titem VALUES (6,1,6,500);
INSERT INTO titem VALUES (7,2,6,500);
INSERT INTO titem VALUES (8,3,7,500);

COMMIT;



SELECT * FROM TCONTRATO;

UPDATE TCONTRATO SET  DATA = SYSDATE, COD_ALUNO = 1, total = 955, desconto = 37 WHERE cod_contrato = 5;

COMMIT;


SELECT * FROM taluno;

UPDATE TALUNO SET CIDADE = 'Santa Maria' WHERE UPPER(CIDADE) = 'MINAS GERAIS';

