-- Created on 3/14/2020 by DIEGO


 CREATE TABLE TESTE
 (
  CODIGO INTEGER NOT NULL PRIMARY KEY,
  DATA DATE DEFAULT SYSDATE
  );
 
 --------------------------------------
 
 INSERT INTO TESTE (CODIGO) VALUES (1);
 COMMIT;
 
 ---------------------------------------
 
 SELECT * FROM TESTE;
 
 SELECT * FROM USER_TABLES;
 
 SELECT * FROM ALL_TABLES;
 
 ----------------------------------------
 
 CREATE TABLE TCONTRATO_VIP
 AS
 SELECT * FROM TCONTRATO WHERE TOTAL > 955;
 
 SELECT * FROM TCONTRATO_VIP;
 
 ----------------------------------------
 
 ALTER TABLE TCONTRATO_VIP ADD VALOR NUMBER(5,2);
 
 ALTER TABLE TCONTRATO_VIP MODIFY VALOR NUMBER(8,2);
 
 ALTER TABLE TCONTRATO_VIP MODIFY VALOR NUMBER(12,2) DEFAULT 0;
 
 ALTER TABLE TCONTRATO_VIP RENAME COLUMN VALOR TO VALOR2; 
 
 ALTER TABLE TCONTRATO_VIP DROP COLUMN VALOR2;
 
 RENAME TCONTRATO TO TCONTRATO_TOP;
 
 SELECT * FROM TCONTRATO_TOP;
 
 RENAME TCONTRATO_TOP TO TCONTRATO;
 
 SELECT * FROM TCONTRATO;
 
 TRUNCATE TABLE TCONTRATO_VIP;
 
 DROP TABLE TCONTRATO_VIP;
 
 SELECT * FROM TCONTRATO;
 
 ---------------------------------------------------------------------
 
 COMMENT ON TABLE TCONTRATO IS 'Informações de Contratos'; 
 
 COMMENT ON COLUMN TCONTRATO.COD_CONTRATO IS 'Código do Contrato';
 
 COMMENT ON COLUMN TCONTRATO.DATA IS 'Data de Emissão do Contrato';
 
 ---------------------------------------------------------------------

 SELECT * FROM USER_COL_COMMENTS;
 
 SELECT * FROM USER_TAB_COMMENTS;
 
 ALTER TABLE TCONTRATO ADD TOTAL2 NUMERIC(8,2);
 
 
 -- Depois não tem como habilitar novamente --
 ALTER TABLE TCONTRATO SET UNUSED (TOTAL2);
 
 ALTER TABLE TCONTRATO DROP UNUSED COLUMNS;
 
 TRUNCATE TABLE TCONTRATO;
 
