
SELECT * FROM TALUNO;

CREATE SEQUENCE SEQ_ALUNO1
START WITH 60

INCREMENT BY 2

MINVALUE 60

MAXVALUE 100

NOCACHE

NOCYCLE;

INSERT INTO TALUNO(COD_ALUNO, NOME) VALUES (SEQ_ALUNO1.NEXTVAL, 'Joana');
INSERT INTO TALUNO(COD_ALUNO, NOME) VALUES (SEQ_ALUNO1.NEXTVAL, 'Maria');
INSERT INTO TALUNO(COD_ALUNO, NOME) VALUES (SEQ_ALUNO1.NEXTVAL, 'Eliane');

SELECT * FROM USER_SEQUENCES;

SELECT SEQ_ALUNO1.CURRVAL FROM DUAL;

DROP SEQUENCE SEQ_ALUNO1;

CREATE SEQUENCE SEQ_ALUNO1 START WITH 80;