SELECT * FROM DUAL;

SELECT SYSDATE FROM DUAL;

SELECT ROUND(45.925, 2),
       TRUNC(45.929, 2),
       MOD(10, 2) AS "Resto da Divisão",
       TRUNC(1.99),
       TRUNC(1.99, 2) 
FROM DUAL;

SELECT * FROM TCONTRATO;


SELECT data, 
       SYSDATE, 
       DATA + 5, 
       SYSDATE - DATA AS DIF_DIAS, 
       TRUNC(SYSDATE - DATA) AS DIAS, 
       SYSDATE + 2 / 24 AS ADD_HORAS, 
       SYSDATE + 15 / 1440 AS ADD_MINUTOS, 
       SYSDATE + 30 / (3600 * 24) AS ADD_SEGUNDOS 
FROM TCONTRATO;


SELECT TRUNC(SYSDATE) FROM DUAL;

SELECT MONTHS_BETWEEN(SYSDATE,SYSDATE-90) AS DIF_MES FROM DUAL;

SELECT ADD_MONTHS(SYSDATE, 5) AS ADICIONA_MES_DATA FROM DUAL;

SELECT NEXT_DAY(SYSDATE, 'SUNDAY') AS ULTIMO_DIA_MES FROM DUAL;

SELECT LAST_DAY(SYSDATE) AS PRIMEIRO_DIA_PROXIMO_MES FROM DUAL;

SELECT ROUND(SYSDATE,'MONTH') AS PRIMEIRO_DIA_PROXIMO_MES FROM DUAL;

SELECT TRUNC(SYSDATE,'MONTH') AS "PRIMEIRO DIA MÊS CORRENTE" FROM DUAL;

-- FORMATANDO DATAS -- 

SELECT to_char(SYSDATE, 'DD') FROM DUAL;

SELECT to_char(SYSDATE, 'DD/MM/YYYY') DATA FROM DUAL;

SELECT to_char(SYSDATE, 'DD/MM') DIA_MES FROM DUAL;

SELECT to_char(SYSDATE, 'DD') DIA FROM DUAL;

SELECT to_char(SYSDATE, 'MM') MES FROM DUAL;

SELECT to_char(SYSDATE, 'YYYY') ANO FROM DUAL;

SELECT to_char(SYSDATE, 'YY') ANO FROM DUAL;

SELECT to_char(SYSDATE, 'MONTH') MES1 FROM DUAL;

SELECT to_char(SYSDATE, 'D') DIA FROM DUAL;

SELECT to_char(SYSDATE, 'DY') DIA_SEMANA FROM DUAL;

SELECT to_char(SYSDATE, 'DAY') DIA_SEMANA1 FROM DUAL;

SELECT to_char(SYSDATE, 'YEAR') ANO FROM DUAL;

SELECT to_char(SYSDATE, ' "NOVO HAMBURGO", fmDAY "," DD "de" fmMonth "de" YYYY ') FROM DUAL;

SELECT to_char(SYSDATE, 'HH24:MI') HORA_MIN FROM DUAL;

SELECT to_char(SYSDATE, 'HH24:MI:SS') HORA_MIN_SEG FROM DUAL;

SELECT to_char(SYSDATE, 'DD/MM HH24:MI') DATA_HORA FROM DUAL;

SELECT to_char(SYSDATE, 'DD/MM/YYYY HH24:MI:SS') DATA_HORA FROM DUAL;

SELECT TRIM(to_char(SALARIO,'L99999.99')), TRIM(TO_CHAR(SALARIO,'L99G999D99')) FROM TALUNO;

SELECT 'R$ ' || (ROUND(SALARIO,2)) AS SALARIO FROM TALUNO;

SELECT LPAD(TRIM((to_char(5000,'L99999.99'))),'12','') FROM DUAL;


-- NVL e NVL2

SELECT t.total, 
       t.desconto, 
       t.desconto + t.total, 
       NVL(t.desconto,0), 
       NVL(t.desconto,0) + t.total,
       NVL2(t.desconto, t.total, -1) 
FROM TCONTRATO t;

SELECT * FROM TALUNO;

UPDATE TALUNO SET ESTADO = 'SC' WHERE COD_ALUNO = 2;

SELECT cod_aluno, NVL(nome, 'SEM NOME') FROM TALUNO;

UPDATE TALUNO SET ESTADO = 'AC' WHERE COD_ALUNO = 2;

-- UPDATE TALUNO SET ESTADO = 'SC' WHERE COD_ALUNO = 


SELECT a.estado, count(*) FROM TALUNO a GROUP BY a.estado ORDER BY a.estado;

SELECT * FROM TALUNO;

SELECT NVL(nome, 'SEM REGISTRO') AS NOME, estado,
       CASE
            WHEN ESTADO = 'PE' THEN 'PERNAMBUCANO'
            WHEN UPPER(ESTADO) = 'SP' THEN 'PAULISTA'
            WHEN ESTADO = 'SC' OR SALARIO > 900 AND SALARIO < 1300 THEN 'CATARINENSE' 
            ELSE 'MINEIRO'
       END AS APELIDO               
FROM TALUNO;

SELECT SYSDATE AS DATA FROM DUAL;

SELECT nome, estado,
DECODE(estado, 'PE','PERNAMBUCANO', 
                      'SP','PAULISTA', 
                      'SC','CATARINENSE', 
                      'MG','MINEIRO') AS APELIDO 
FROM TALUNO;


